DROP FUNCTION IF EXISTS FN_EMBARCADOR_DATA_PREVISAO;

DELIMITER //
    CREATE FUNCTION FN_EMBARCADOR_DATA_PREVISAO(SPA_PRAZO_DIAS INT) RETURNS DATE
    BEGIN
        DECLARE SPV_PRAZO_DIAS_CORRIDOS,SPV_FERIADO INT DEFAULT 0;
        WHILE SPA_PRAZO_DIAS > 0 DO
            SET SPV_PRAZO_DIAS_CORRIDOS = (SPV_PRAZO_DIAS_CORRIDOS + 1);
            SELECT COUNT(*) INTO SPV_FERIADO FROM embarcador_feriados F WHERE F.data=DATE_ADD(NOW(), INTERVAL SPV_PRAZO_DIAS_CORRIDOS DAY);
            IF SPV_FERIADO = 0 THEN
                SET SPA_PRAZO_DIAS = (SPA_PRAZO_DIAS - 1);
            END IF;
        END WHILE;
        RETURN DATE_ADD(NOW(), INTERVAL SPV_PRAZO_DIAS_CORRIDOS DAY);
    END //
DELIMITER ;

