DROP PROCEDURE IF EXISTS SP_EMBARCADOR_DATA_PREVISAO;

DELIMITER //
    CREATE PROCEDURE SP_EMBARCADOR_DATA_PREVISAO(IN SPA_ENCOMENDA_ID INT, IN SPA_PRAZO_DIAS INT)
    BEGIN
        DECLARE SPV_PRAZO_DIAS_CORRIDOS,SPV_FERIADO INT DEFAULT 0;
        DECLARE DATA_DIA DATE;
        WHILE SPA_PRAZO_DIAS > 0 DO
            SET SPV_PRAZO_DIAS_CORRIDOS = (SPV_PRAZO_DIAS_CORRIDOS + 1);
            SELECT COUNT(*) INTO SPV_FERIADO FROM embarcador_feriados F WHERE F.data=DATE_ADD(NOW(), INTERVAL SPV_PRAZO_DIAS_CORRIDOS DAY);
            IF SPV_FERIADO = 0 THEN
                SET SPA_PRAZO_DIAS = (SPA_PRAZO_DIAS - 1);
            END IF;
        END WHILE;
        UPDATE embarcador_encomendas SET data_previsao = DATE_ADD(NOW(), INTERVAL SPV_PRAZO_DIAS_CORRIDOS DAY) WHERE id=SPA_ENCOMENDA_ID;
    END //
DELIMITER ;

